hsilan-sui/everforest-backend

dev.js
=> fix: 刪除初期測試的dev.js

app.js
=> chore: test

.github/CODEOWNERS
=> 創建CODEOWNERS

app.js, controller/auth.js, docker-compose.yml, entities/Member.js, package-lock.json, package.json, routes/authRouter.js, utils/appError.js, utils/errorAsync.js, utils/validUtils.js
=> feat: 新增註冊功能及app.js設定

utils/appError.js, utils/validUtils.js
=> fix: 函式表達式

app.js, middlewares/isAuth.js, utils/jwtUtils.js
- 新增middlewares資料夾=>新增isAuth middleware ->兩個方法來處理 1.是否登入 2.驗證角色
=> feat: 加入jwt驗證功能&新增middlewarwares資料夾 =>驗證登入的isAuth&驗證登入角色restrictTo 

app.js, controllers/auth/authController.js, docker-compose.yml, entities/event/EventInfo.js, entities/host/HostInfo.js, entities/member/MemberAuthProvider.js, entities/member/MemberInfo.js, package-lock.json, package.json, routes/authRouter.js, swagger.js, utils/jwtUtils.js
- 修正了member_info資料表欄位 對照過 API文件(註冊 登入)
- 加入了swagger文件 方便前端可以讀文件
=> Feature/bk sui/fix directory structure

config/secret.js, controllers/hostController.js, controllers/memberController.js, package-lock.json, package.json, routes/hostRouter.js, routes/memberRouter.js, utils/uploadImage.js
api + swagger
- 新增會員頭貼
- 新增主辦方頭貼及封面照
- 新增主辦方封面照
=> feat: 新增會員頭貼及主辦方頭貼及封面照api

.github/CODEOWNERS, entities/event/EventInfo.js, entities/event/EventInfoPhoto.js, entities/event/EventTag.js, entities/event/EventTagInfo.js, entities/host/HostInfo.js
=> Feature/bk sui/create events

config/secret.js, controllers/hostController.js, controllers/memberController.js, package-lock.json, package.json, routes/hostRouter.js, routes/memberRouter.js, utils/uploadImage.js, zeabur-template.yml
=> Feature/bk helena/member avatar

controllers/authController.js
=> Feature/bk helena/fix (#31)

controllers/authController.js
=> Feature/bk helena/fix (#33)

.github/CODEOWNERS, Dockerfile, app.js
=> Feature/bk helena/fix (#35)

package-lock.json
=> Feature/bk helena/fix (#37)

controllers/memberController.js
=> fix: 更新會員欄位

app.js, config/secret.js, controllers/eventController.js, controllers/eventTagController.js, entities/event/EventComment.js, entities/event/EventInfo.js, entities/event/EventInfoPhoto.js, entities/event/EventNotice.js, entities/event/EventPlan.js, entities/event/EventPlanAddon.js, entities/event/EventPlanContent.js, entities/event/EventTag.js, entities/member/MemberInfo.js, routes/eventsRouter.js, routes/metaRouter.js, utils/uploadImage.js
=> Feature/bk sui/events fn

controllers/authController.js, package.json, routes/authRouter.js
=> feat: add reset password api

controllers/authController.js, controllers/eventController.js, routes/eventsRouter.js
=> fix: member register & event list

controllers/eventController.js, controllers/memberController.js
* fix: member register & event list
* feat: 新增活動人數篩選及儲存 memeber 資料
=> Feature/bk helena/fix member auth (#51)

config/secret.js, controllers/eventController.js, entities/event/EventInfo.js, entities/event/EventTag.js, entities/event/EventTagInfo.js
- fix: 把eventTag和eventTagInfo回傳的資料也加入到[主辦方]取得自己的單筆活動詳情這支api的回傳內容中
- 公開取得已經發佈的活動api重組資料
=> Feature/bk sui/update host events

app.js, controllers/orderController.js, entities/order/OrderInfo.js, entities/order/OrderPay.js, entities/order/OrderTicket.js, package-lock.json, package.json, routes/orderRouter.js
- 新增金流串接
- 新增 orderInfo orderPay orderTicket 資料表
=> Feature/bk helena/payment

app.js, controllers/adminController.js, package.json, routes/adminRouter.js, scripts/seedAdmin.js
=> Feature/bk sui/admin role

controllers/orderController.js, entities/event/EventPlan.js, routes/orderRouter.js
1.新增swagger UI FOR  MemberOrder/OrderTicket
2.新增 route getMemberOrder加上 status
=> Feature/bk rubio/fix get order ticket

utils/emailUtils.js
=> Feature/bk sui/email

middlewares/checkEventEditable.js, routes/eventsRouter.js
feat: middlewares checkEventEditable加上報名截止時間已過，禁止編輯
=> Fix/bk sui/check event editable

controllers/orderController.js
postOrderTicket 判斷票券已存在時回傳的格式要和新增票券的格式一致
=> fix: postOrderTicket 判斷票券已存在時回傳的格式要和新增票券的格式一致
